/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LumaApp {
    }
    interface LumaDocRenderer {
        /**
          * @default ''
         */
        "page": string;
        /**
          * @default ''
         */
        "section": string;
    }
    interface LumaDropdown {
        /**
          * @default []
         */
        "items": any[];
        /**
          * @default 'No options available'
         */
        "noOptionsText": string;
        /**
          * @default 'Select an option'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface LumaLink {
        /**
          * @default '/'
         */
        "href": string;
    }
    interface LumaPage {
        /**
          * @default 'Untitled Page'
         */
        "label": string;
        /**
          * @default false
         */
        "noScroll": boolean;
    }
    interface LumaPageContent {
    }
    interface LumaPageNav {
        /**
          * @default []
         */
        "items": PageNavigationItem[];
    }
    interface PageDocs {
    }
    interface PageNotFound {
    }
    interface PagePlayground {
    }
}
export interface LumaDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLumaDropdownElement;
}
export interface LumaPageNavCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLumaPageNavElement;
}
declare global {
    interface HTMLLumaAppElement extends Components.LumaApp, HTMLStencilElement {
    }
    var HTMLLumaAppElement: {
        prototype: HTMLLumaAppElement;
        new (): HTMLLumaAppElement;
    };
    interface HTMLLumaDocRendererElement extends Components.LumaDocRenderer, HTMLStencilElement {
    }
    var HTMLLumaDocRendererElement: {
        prototype: HTMLLumaDocRendererElement;
        new (): HTMLLumaDocRendererElement;
    };
    interface HTMLLumaDropdownElementEventMap {
        "itemChanged": string;
    }
    interface HTMLLumaDropdownElement extends Components.LumaDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLumaDropdownElementEventMap>(type: K, listener: (this: HTMLLumaDropdownElement, ev: LumaDropdownCustomEvent<HTMLLumaDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLumaDropdownElementEventMap>(type: K, listener: (this: HTMLLumaDropdownElement, ev: LumaDropdownCustomEvent<HTMLLumaDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLumaDropdownElement: {
        prototype: HTMLLumaDropdownElement;
        new (): HTMLLumaDropdownElement;
    };
    interface HTMLLumaLinkElement extends Components.LumaLink, HTMLStencilElement {
    }
    var HTMLLumaLinkElement: {
        prototype: HTMLLumaLinkElement;
        new (): HTMLLumaLinkElement;
    };
    interface HTMLLumaPageElement extends Components.LumaPage, HTMLStencilElement {
    }
    var HTMLLumaPageElement: {
        prototype: HTMLLumaPageElement;
        new (): HTMLLumaPageElement;
    };
    interface HTMLLumaPageContentElement extends Components.LumaPageContent, HTMLStencilElement {
    }
    var HTMLLumaPageContentElement: {
        prototype: HTMLLumaPageContentElement;
        new (): HTMLLumaPageContentElement;
    };
    interface HTMLLumaPageNavElementEventMap {
        "itemsChanged": PageNavigationItem[];
    }
    interface HTMLLumaPageNavElement extends Components.LumaPageNav, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLumaPageNavElementEventMap>(type: K, listener: (this: HTMLLumaPageNavElement, ev: LumaPageNavCustomEvent<HTMLLumaPageNavElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLumaPageNavElementEventMap>(type: K, listener: (this: HTMLLumaPageNavElement, ev: LumaPageNavCustomEvent<HTMLLumaPageNavElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLumaPageNavElement: {
        prototype: HTMLLumaPageNavElement;
        new (): HTMLLumaPageNavElement;
    };
    interface HTMLPageDocsElement extends Components.PageDocs, HTMLStencilElement {
    }
    var HTMLPageDocsElement: {
        prototype: HTMLPageDocsElement;
        new (): HTMLPageDocsElement;
    };
    interface HTMLPageNotFoundElement extends Components.PageNotFound, HTMLStencilElement {
    }
    var HTMLPageNotFoundElement: {
        prototype: HTMLPageNotFoundElement;
        new (): HTMLPageNotFoundElement;
    };
    interface HTMLPagePlaygroundElement extends Components.PagePlayground, HTMLStencilElement {
    }
    var HTMLPagePlaygroundElement: {
        prototype: HTMLPagePlaygroundElement;
        new (): HTMLPagePlaygroundElement;
    };
    interface HTMLElementTagNameMap {
        "luma-app": HTMLLumaAppElement;
        "luma-doc-renderer": HTMLLumaDocRendererElement;
        "luma-dropdown": HTMLLumaDropdownElement;
        "luma-link": HTMLLumaLinkElement;
        "luma-page": HTMLLumaPageElement;
        "luma-page-content": HTMLLumaPageContentElement;
        "luma-page-nav": HTMLLumaPageNavElement;
        "page-docs": HTMLPageDocsElement;
        "page-not-found": HTMLPageNotFoundElement;
        "page-playground": HTMLPagePlaygroundElement;
    }
}
declare namespace LocalJSX {
    interface LumaApp {
    }
    interface LumaDocRenderer {
        /**
          * @default ''
         */
        "page"?: string;
        /**
          * @default ''
         */
        "section"?: string;
    }
    interface LumaDropdown {
        /**
          * @default []
         */
        "items"?: any[];
        /**
          * @default 'No options available'
         */
        "noOptionsText"?: string;
        "onItemChanged"?: (event: LumaDropdownCustomEvent<string>) => void;
        /**
          * @default 'Select an option'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface LumaLink {
        /**
          * @default '/'
         */
        "href"?: string;
    }
    interface LumaPage {
        /**
          * @default 'Untitled Page'
         */
        "label"?: string;
        /**
          * @default false
         */
        "noScroll"?: boolean;
    }
    interface LumaPageContent {
    }
    interface LumaPageNav {
        /**
          * @default []
         */
        "items"?: PageNavigationItem[];
        "onItemsChanged"?: (event: LumaPageNavCustomEvent<PageNavigationItem[]>) => void;
    }
    interface PageDocs {
    }
    interface PageNotFound {
    }
    interface PagePlayground {
    }
    interface IntrinsicElements {
        "luma-app": LumaApp;
        "luma-doc-renderer": LumaDocRenderer;
        "luma-dropdown": LumaDropdown;
        "luma-link": LumaLink;
        "luma-page": LumaPage;
        "luma-page-content": LumaPageContent;
        "luma-page-nav": LumaPageNav;
        "page-docs": PageDocs;
        "page-not-found": PageNotFound;
        "page-playground": PagePlayground;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "luma-app": LocalJSX.LumaApp & JSXBase.HTMLAttributes<HTMLLumaAppElement>;
            "luma-doc-renderer": LocalJSX.LumaDocRenderer & JSXBase.HTMLAttributes<HTMLLumaDocRendererElement>;
            "luma-dropdown": LocalJSX.LumaDropdown & JSXBase.HTMLAttributes<HTMLLumaDropdownElement>;
            "luma-link": LocalJSX.LumaLink & JSXBase.HTMLAttributes<HTMLLumaLinkElement>;
            "luma-page": LocalJSX.LumaPage & JSXBase.HTMLAttributes<HTMLLumaPageElement>;
            "luma-page-content": LocalJSX.LumaPageContent & JSXBase.HTMLAttributes<HTMLLumaPageContentElement>;
            "luma-page-nav": LocalJSX.LumaPageNav & JSXBase.HTMLAttributes<HTMLLumaPageNavElement>;
            "page-docs": LocalJSX.PageDocs & JSXBase.HTMLAttributes<HTMLPageDocsElement>;
            "page-not-found": LocalJSX.PageNotFound & JSXBase.HTMLAttributes<HTMLPageNotFoundElement>;
            "page-playground": LocalJSX.PagePlayground & JSXBase.HTMLAttributes<HTMLPagePlaygroundElement>;
        }
    }
}
